title: "Sai Kalyan Yalla"
description: "Analytics Engineer and Data Operations, Boston MA"
# Use the built-in GitHub Pages theme, still serves our custom layout
# (the layout below does not depend on the theme styles)
theme: minima


# Optional branding shown by some themes (safe to keep even if unused)
logo: /headshot.jpg
show_downloads: false


# If you add Google Analytics later, set the ID here
# google_analytics: G-XXXXXXXXXX



# Site links for the footer or future use
links:
github: https://github.com/kalyan1210
linkedin: https://www.linkedin.com/in/saikalyanyalla/
email: mailto:yalla.saikalyan@gmail.com
